spring.application.name=CRM-Manara
spring.datasource.url=jdbc:mariadb://localhost:3306/manara?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# MODIFIED
spring.mail.host=smtp.gmail.com
# MODIFIED
spring.mail.port=587
# ADDED
spring.mail.username=bafingsimbokeita@gmail.com
# ADDED
spring.mail.password=unre lgbw mwhf pldb
# MODIFIED
spring.mail.properties.mail.smtp.auth=true
# MODIFIED
spring.mail.properties.mail.smtp.starttls.enable=true

# ADDED
spring.security.oauth2.client.registration.google.client-id=your-google-client-id
# ADDED
spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
# ADDED
spring.security.oauth2.client.registration.google.scope=email,profile
